<?php

/**
 * @file
 * NFA Tracker hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nfa_tracker_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['revision']['#access']) {
    // Ensure people cannot uncheck the revision requirement.
    $form['revision']['#attributes']['disabled'] = true;
    $form['revision']['#value'] = true;
    $form['revision_log']['#states'] = [];
    $form['revision_log']['#required'] = true;
    $form['revision_log']['widget']['#required'] = true;
    $form['revision_log']['widget'][0]['#required'] = true;
    $form['revision_log']['widget'][0]['value']['#required'] = true;
  }
}
